import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


def load_config_from_ini(env_path: Path) -> dict[str, Any]:
    """
    Lê um ficheiro .ini e retorna um dicionário com as configurações.
    É uma implementação simples e robusta, sem dependências externas.
    Args:
        env_path (Path): O caminho para o ficheiro .ini.
    Returns:
        dict[str, Any]: Um dicionário contendo as variáveis de ambiente carregadas.
    """
    if not env_path.is_file():
        # Levanta um erro se o ficheiro .ini não for encontrado.
        # Isto é melhor do que falhar silenciosamente.
        raise FileNotFoundError(f'Configuration file "{env_path.name}" not found at path: "{env_path}"')

    config = {}
    with open(env_path, 'r', encoding='utf-8') as f:
        for line in f:
            # Ignora comentários e linhas em branco
            read_line = line.strip()
            if not read_line or read_line.startswith('#'):
                continue

            # Divide a linha na primeira ocorrência de '='
            if '=' in read_line:
                key, value = read_line.split('=', 1)

                # Remove aspas (simples ou duplas) do valor
                if value.startswith('"') and value.endswith('"'):
                    value = value[1:-1]
                elif value.startswith("'") and value.endswith("'"):
                    value = value[1:-1]

                config[key.strip()] = value.strip()

    return config


def create_config_file(config_path: Path, api_url: str, credentials: dict[str, Any]) -> None:
    """
    Cria e escreve o ficheiro de configuração (config.ini) com as credenciais fornecidas.
    Levanta uma exceção em caso de erro.

    Args:
        credentials (Dict[str, Any]): Um dicionário contendo as credenciais da API.
    Returns:
        None
    """
    config_file = config_path / 'config.ini'

    try:
        logger.info(f'Creating configuration file at: {config_path}')

        with open(config_file, 'w', encoding='utf-8') as f:
            f.write('# Application Configuration File\n')
            f.write('# This file is automatically generated.\n\n')
            f.write('# API connection parameters\n')
            f.write(f'SERVER_BASE_ADDRESS={api_url}\n')
            f.write(f'API_KEY={credentials.get("appKey", "")}\n')
            f.write(f'API_SECRET={credentials.get("appSecret", "")}\n')
            f.write(f'CLIENT_ID={credentials.get("clientId", "")}\n\n')
            f.write('# Environment settings\n')
            f.write('PRODUCTION=True\n\n')
            f.write('# Debug settings\n')
            f.write('DEBUG=False\n\n')
            f.write('# Internationalization settings\n')
            f.write('# Debug settings\n')
            f.write('DEFAULT_LANGUAGE=en_GB\n')
            f.write('SUPPORTED_LANGUAGES=en,en_GB,pt_PT,de_DE\n')
        logger.info('Configuration file created successfully.')
    except IOError as e:
        error_msg = f'Failed to write to configuration file: {e}'
        logger.exception(error_msg)
        # Re-levanta a exceção para que o chamador possa tratá-la
        raise IOError(error_msg) from e
